[package]
name = "eurochef-filelist"
version = "0.1.0"
authors = ["cohaereo <cohaereo@protonmail.com>"]
edition = "2021"
rust-version = "1.65"

[dependencies]
anyhow = "1"
binrw = "0.13.3"
itertools = "0.10"
